### Localhost Routes

# Home Page Message Screen
GET http://localhost:8080

# Get all contacts
GET http://localhost:8080/professional

# Get a specific contact by ID
GET http://localhost:8080/professional/66eb2c7a94acf0e55fcfb1f2

# Get a specific contact by ID
GET http://localhost:8080/professional/66ef447751de745f6b97cd7d


### Published Routes

# Home Page Message Screen
GET https://professionals-project.onrender.com

# Get all contacts
GET https://professionals-project.onrender.com/professional

# Get a specific contact by ID
GET https://professionals-project.onrender.com/professional/66eb2c7a94acf0e55fcfb1f2

# Get a specific contact by ID
GET https://professionals-project.onrender.com/professional/66ef447751de745f6b97cd7d