// LOCALHOST -Vendors

### Get All Vendors
GET http://localhost:8080/vendors

### Get Single Vendors
GET http://localhost:8080/vendors/66fddd383b61ee03925210ec

### Create Vendor
POST http://localhost:8080/vendors HTTP/1.1
Content-Type: application/json

{
  "vendorName": "XYX Fitness",
  "contact": "Sarah Johnson",
  "position": "Marketing Director",
  "contactPhone": "987-654-3210",
  "contactEmail": "sarah.johnson@xyx.com",
  "streetAddress": "456 Oak Avenu",
  "city": "Smallville",
  "state": "Texas",
  "zipCode": 54321,
  "notes": "Need flyers for front desk."
}

### Update Vendor

### Delete Vendor
DELETE http://localhost:8080/vendors/66fddd383b61ee03925210ec

# LOCALHOST -App Users

### Get all App Users
GET http://localhost:8080/appUsers 

### Get a Single App User with the ID
GET http://localhost:8080/appUsers/66fde3548005f51071e2967f

### Create App User
POST http://localhost:8080/appUsers HTTP/1.1
Content-Type: application/json

{
  "firstName": "Lenora",
  "lastName": "Stevens",
  "email": "LS@any.com",
  "phone": "999-888-7777"
}

### Update App User

### Delete App User
DELETE http://localhost:8080/appUsers/66fde3548005f51071e2967f

// RENDER LINKS - Vendors

### Get All Vendors Live Link
GET https://vendor-tracking.onrender.com/vendors

### Get a Single Vendor with the ID
GET https://vendor-tracking.onrender.com/vendors/66fddfa9c185afdfc60f9695

### Create Vendor
POST https://vendor-tracking.onrender.com/vendors HTTP/1.1
Content-Type: application/json

{
  "vendorName": "XYX Fitness",
  "contact": "Sarah Johnson",
  "position": "Marketing Director",
  "contactPhone": "987-654-3210",
  "contactEmail": "sarah.johnson@xyx.com",
  "streetAddress": "456 Oak Avenu",
  "city": "Smallville",
  "state": "Texas",
  "zipCode": 54321,
  "notes": "Need flyers for front desk."
}

### Update Vendor

### Delete Vendor
DELETE https://vendor-tracking.onrender.com/vendors/66fddfa9c185afdfc60f9695
# RENDER LINKS - App Users

### Get All App Users
GET https://vendor-tracking.onrender.com/appUsers

### Get a Single App Users with the ID
GET https://vendor-tracking.onrender.com/appUsers/66fc97be169249918d78bf63

### Create App User
POST https://vendor-tracking.onrender.com/appUsers HTTP/1.1
Content-Type: application/json

{
  "firstName": "Lenora",
  "lastName": "Stevens",
  "email": "LS@any.com",
  "phone": "999-888-7777"
}

### Update App User

### Delete Vendor
DELETE https://vendor-tracking.onrender.com/appUsers/66fc97be169249918d78bf63