// LOCALHOST -Vendors

### Get All Vendors
GET http://localhost:8080/vendors

### Get Single Vendors
GET http://localhost:8080/vendors/66fdbcf971f575fb48af3707

### Create Vendor
POST http://localhost:8080/vendors HTTP/1.1
Content-Type: application/json

{
  "vendorName": "XYX Fitness",
  "contact": "Sarah Johnson",
  "position": "Marketing Director",
  "contactPhone": "987-654-3210",
  "contactEmail": "sarah.johnson@xyx.com",
  "streetAddress": "456 Oak Avenu",
  "city": "Smallville",
  "state": "Texas",
  "zipCode": 54321,
  "notes": "Need flyers for front desk."
}

### Update Vendor
PUT http://localhost:8080/vendors/66fdbcf971f575fb48af3707 HTTP/1.1
Content-Type: application/json

{
  "vendorName": "XYX Fitness",
  "contact": "Mike Johnson",
  "position": "Marketing Director",
  "contactPhone": "987-654-3210",
  "contactEmail": "mike.johnson@xyx.com",
  "streetAddress": "456 Oak Avenu",
  "city": "Smallville",
  "state": "Texas",
  "zipCode": 54321,
  "notes": "Received flyers for front desk."
}

### Delete Vendor
DELETE http://localhost:8080/vendors/66fddd383b61ee03925210ec

# LOCALHOST -App Users

### Get all App Users
GET http://localhost:8080/appUsers 

### Get a Single App User with the ID
GET http://localhost:8080/appUsers/66fdeebf893263f131ee59dc

### Create App User
POST http://localhost:8080/appUsers HTTP/1.1
Content-Type: application/json

{
  "firstName": "Brandon",
  "lastName": "Stevens",
  "email": "BS@any.com",
  "phone": "999-888-7777"
}

### Update App User
PUT http://localhost:8080/appUsers/66fdeebf893263f131ee59dc HTTP/1.1
Content-Type: application/json

{
  "firstName": "Connor",
  "lastName": "Stevens",
  "email": "CS@any.com",
  "phone": "999-888-7777"
}

### Delete App User
DELETE http://localhost:8080/appUsers/66fdeebf893263f131ee59dc



// RENDER LINKS - Vendors

### Get All Vendors Live Link
GET https://vendor-tracking.onrender.com/vendors

### Get a Single Vendor with the ID
GET https://vendor-tracking.onrender.com/vendors/66fddfa9c185afdfc60f9695

### Create Vendor
POST https://vendor-tracking.onrender.com/vendors HTTP/1.1
Content-Type: application/json

{
  "vendorName": "XYX Fitness",
  "contact": "Sarah Johnson",
  "position": "Marketing Director",
  "contactPhone": "987-654-3210",
  "contactEmail": "sarah.johnson@xyx.com",
  "streetAddress": "456 Oak Avenu",
  "city": "Smallville",
  "state": "Texas",
  "zipCode": 54321,
  "notes": "Need flyers for front desk."
}

### Update Vendor
PUT https://vendor-tracking.onrender.com/vendors/66fddfa9c185afdfc60f9695 HTTP/1.1
Content-Type: application/json

{
  "vendorName": "XYX Fitness",
  "contact": "Sarah Johnson",
  "position": "Marketing Director",
  "contactPhone": "987-654-3210",
  "contactEmail": "sarah.johnson@xyx.com",
  "streetAddress": "456 Oak Avenu",
  "city": "Smallville",
  "state": "Texas",
  "zipCode": 54321,
  "notes": "Need flyers for front desk."
}

### Delete Vendor
DELETE https://vendor-tracking.onrender.com/vendors/66fddfa9c185afdfc60f9695



# RENDER LINKS - App Users

### Get All App Users
GET https://vendor-tracking.onrender.com/appUsers

### Get a Single App Users with the ID
GET https://vendor-tracking.onrender.com/appUsers/66fdef53b8827680a75a905f

### Create App User
POST https://vendor-tracking.onrender.com/appUsers HTTP/1.1
Content-Type: application/json

{
  "firstName": "Connie",
  "lastName": "Stevens",
  "email": "CS@any.com",
  "phone": "999-888-7777"
}

### Update App User
PUT https://vendor-tracking.onrender.com/appUsers/66fdef53b8827680a75a905f HTTP/1.1
Content-Type: application/json

{
  "firstName": "Ethan",
  "lastName": "Stevens",
  "email": "ES@any.com",
  "phone": "999-888-7777"
}

### Delete Vendor
DELETE https://vendor-tracking.onrender.com/appUsers/66fc97be169249918d78bf63