// LOCALHOST 

### Get All Vendors
GET http://localhost:8080/vendors

### Get Single Vendor
GET http://localhost:8080/vendors/66fc9ac0169249918d78bf64

### Create Vendor
POST http://localhost:8080/vendors HTTP/1.1
Content-Type: application/json

{
  "vendorName": "XYX Fitness",
  "contact": "Sarah Johnson",
  "position": "Marketing Director",
  "contactPhone": "987-654-3210",
  "contactEmail": "sarah.johnson@xyx.com",
  "streetAddress": "456 Oak Avenu",
  "city": "Smallville",
  "state": "Texas",
  "zipCode": 54321,
  "notes": "Need flyers for front desk."
}

### Get all App Users
GET http://localhost:8080/appUsers 

### Get a Single App User with the ID
GET http://localhost:8080/appUsers/66fc97be169249918d78bf63

### Create App User
POST http://localhost:8080/appUsers HTTP/1.1
Content-Type: application/json

{
  "firstName": "Lenora",
  "lastName": "Stevens",
  "email": "LS@any.com",
  "phone": "999-888-7777"
}


// RENDER LINKS

### Get All Vendors Live Link
GET https://vendor-tracking.onrender.com/vendors

### Get a Single Vendor with the ID
GET https://vendor-tracking.onrender.com/vendors/66fc9ac0169249918d78bf64

### Get All App Users
GET https://vendor-tracking.onrender.com/appUsers

### Get a Single App Users with the ID
GET https://vendor-tracking.onrender.com/appUsers/66fc97be169249918d78bf63